language: java

before_script:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime
  - haxelib install lime-tools
  - haxelib install openfl
  - haxelib install openfl-native
  - haxelib install openfl-html5
  - haxelib install openfl-tools
  - haxelib run openfl setup linux
  - haxelib install systools
  - haxelib install spinehx
  - haxelib install actuate
  - haxelib install hxcpp
  - haxelib install nape
  - haxelib install task
  - haxelib git firetongue https://github.com/larsiusprime/firetongue
  - haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
  - haxelib git flixel-demos https://github.com/HaxeFlixel/flixel-demos
  - haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools
  - haxelib git flixel-ui https://github.com/HaxeFlixel/flixel-ui dev
  - haxelib dev flixel .

script:
  - haxelib run flixel-tools testdemos
