language: java

env: 
  - TARGET=flash
  - TARGET=neko
  - TARGET=html5

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir ~/haxelib
  - haxelib -notimeout setup ~/haxelib 
  - haxelib -notimeout install munit
  - haxelib -notimeout install lime
  - haxelib -notimeout install lime-tools
  - haxelib -notimeout run lime install openfl
  - haxelib -notimeout install systools
  - haxelib git spinehaxe https://github.com/bendmorris/spinehaxe
  - haxelib -notimeout install nape
  - haxelib -notimeout install task
  - haxelib -notimeout install hscript
  - haxelib git openfl-bitfive https://github.com/YellowAfterlife/openfl-bitfive
  - haxelib git firetongue https://github.com/larsiusprime/firetongue
  - haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools
  - haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons dev
  - haxelib git flixel-ui https://github.com/HaxeFlixel/flixel-ui dev
  - haxelib git flixel https://github.com/HaxeFlixel/flixel dev
  - haxelib dev flixel-demos .

script:
  - haxelib run flixel-tools testdemos -$TARGET
