language: haxe
dist: xenial
services:
  - xvfb

haxe:
  - 3.4.7
  - development

env:
  - TARGET=flash OPENFL=new
  - TARGET=neko  OPENFL=new
  - TARGET=cpp   OPENFL=new
  - TARGET=html5 OPENFL=new

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

before_install:
  - export DISPLAY=:99.0

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel
  - haxelib dev flixel-demos .

script:
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - haxe --cwd ~/haxe/lib/flixel/git/tests --run RunTravis $TARGET $OPENFL
  - kill %1
